var fnt = draw_get_font();
draw_set_font(fnt_comicsans);
var col = draw_get_color();
draw_set_halign(fa_right);
draw_set_color(c_black);
draw_text_transformed(631, 40, string_hash_to_newline(debugmessage), 0.5, 0.5, 0);
draw_set_color(c_red);
draw_text_transformed(630, 39, string_hash_to_newline(debugmessage), 0.5, 0.5, 0);
draw_set_halign(fa_left);
draw_set_color(col);
draw_set_font(fnt);